name: Automated testing for enumext package (TL2024)

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 2024
        command:
          - testpkg
          - examples
          - doc
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run  github-actions-tune
        uses: abbbi/github-actions-tune@v1

      - name: Setup TeX Live ${{ matrix.version }}
        uses: teatimeguest/setup-texlive-action@v3
        with:
          version: ${{ matrix.version }}
          package-file: .github/tl_packages
          cache: true

      - name: Install enumext package
        run: l3build install

      - name: Run "l3build ${{ matrix.command }}" (TeX Live ${{ matrix.version }})
        run: l3build ${{ matrix.command }}

      # If fail some test, upload test and log file
      - name: Upload error files
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: github-error-files
          path: |
            ./*.log
            ./*.tex
          retention-days: 2
